### ISSUE TITLE
can't replicate non XML compatible data

### ISSUE THREAD

**Issue by annalooker** [singer-io/tap-bronto#8]
**Summary**

Encountered an error while attempting to replicate data from . The message was:

_All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters_

**Logs**
2018-10-23 17:03:06,479Z   main - INFO Running tap-bronto version 1.0.2 and target-stitch version 1.7.4
2018-10-23 17:03:06,560Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-bronto --config /tmp/tap_discover_config.json --discover
2018-10-23 17:03:06,806Z    tap - INFO Starting discovery.
2018-10-23 17:03:06,842Z   main - INFO Tap exited normally.
2018-10-23 17:03:06,847Z   main - INFO Saving list of discovered streams
2018-10-23 17:03:06,921Z   main - INFO Saving structure of stream contact
2018-10-23 17:03:07,014Z   main - INFO Saving structure of stream inbound_activity
2018-10-23 17:03:07,102Z   main - INFO Saving structure of stream list
2018-10-23 17:03:07,122Z   main - INFO Saving structure of stream outbound_activity
2018-10-23 17:03:07,171Z   main - INFO Saving structure of stream unsubscribe
2018-10-23 17:03:07,318Z   main - INFO Getting list of selected properties
2018-10-23 17:03:07,368Z   main - DEBUG Getting initial state
2018-10-23 17:03:07,374Z   main - INFO Starting tap: tap-env/bin/tap-bronto --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2018-10-23 17:03:07,384Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2018-10-23 17:03:07,753Z    tap - INFO Starting sync.
2018-10-23 17:03:07,756Z    tap - INFO Logging in
2018-10-23 17:03:07,811Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2018-10-23 17:03:08,120Z    tap - ERROR All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2018-10-23 17:03:08,120Z    tap - ERROR Failed to sync endpoint, moving on!
2018-10-23 17:03:08,120Z    tap - CRITICAL All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2018-10-23 17:03:08,123Z    tap - Traceback (most recent call last):
2018-10-23 17:03:08,123Z    tap -   File "tap-env/bin/tap-bronto", line 11, in <module>
2018-10-23 17:03:08,123Z    tap -     sys.exit(main())
2018-10-23 17:03:08,123Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bronto/__init__.py", line 179, in main
2018-10-23 17:03:08,123Z    tap -     raise exception
2018-10-23 17:03:08,123Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bronto/__init__.py", line 175, in main
2018-10-23 17:03:08,124Z    tap -     do_sync(args)
2018-10-23 17:03:08,124Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bronto/__init__.py", line 124, in do_sync
2018-10-23 17:03:08,124Z    tap -     raise exception
2018-10-23 17:03:08,124Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bronto/__init__.py", line 117, in do_sync
2018-10-23 17:03:08,124Z    tap -     stream_accessor.login()
2018-10-23 17:03:08,124Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bronto/stream.py", line 66, in login
2018-10-23 17:03:08,125Z    tap -     self.config.get('token'))
2018-10-23 17:03:08,125Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/client.py", line 45, in __call__
2018-10-23 17:03:08,125Z    tap -     self._op_name, args, kwargs)
2018-10-23 17:03:08,125Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 110, in send
2018-10-23 17:03:08,125Z    tap -     options=options)
2018-10-23 17:03:08,125Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
2018-10-23 17:03:08,126Z    tap -     serialized = operation_obj.create(*args, **kwargs)
2018-10-23 17:03:08,126Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 197, in create
2018-10-23 17:03:08,126Z    tap -     return self.input.serialize(*args, **kwargs)
2018-10-23 17:03:08,126Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 64, in serialize
2018-10-23 17:03:08,126Z    tap -     self.body.render(body, body_value)
2018-10-23 17:03:08,126Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
2018-10-23 17:03:08,126Z    tap -     self._render_value_item(parent, value, render_path)
2018-10-23 17:03:08,127Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
2018-10-23 17:03:08,127Z    tap -     return self.type.render(node, value, None, render_path)
2018-10-23 17:03:08,127Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
2018-10-23 17:03:08,127Z    tap -     element.render(parent, element_value, child_path)
2018-10-23 17:03:08,127Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
2018-10-23 17:03:08,127Z    tap -     element.render(parent, element_value, child_path)
2018-10-23 17:03:08,128Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
2018-10-23 17:03:08,128Z    tap -     self._render_value_item(parent, value, render_path)
2018-10-23 17:03:08,128Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
2018-10-23 17:03:08,128Z    tap -     return self.type.render(node, value, None, render_path)
2018-10-23 17:03:08,129Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/zeep/xsd/types/simple.py", line 74, in render
2018-10-23 17:03:08,129Z    tap -     parent.text = self.xmlvalue(value)
2018-10-23 17:03:08,129Z    tap -   File "src/lxml/etree.pyx", line 1020, in lxml.etree._Element.text.__set__
2018-10-23 17:03:08,129Z    tap -   File "src/lxml/apihelpers.pxi", line 711, in lxml.etree._setNodeText
2018-10-23 17:03:08,129Z    tap -   File "src/lxml/apihelpers.pxi", line 699, in lxml.etree._createTextNode
2018-10-23 17:03:08,130Z    tap -   File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8
2018-10-23 17:03:08,130Z    tap - ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2018-10-23 17:03:08,173Z target - INFO Exiting normally
2018-10-23 17:03:08,208Z   main - INFO Target exited normally with status 0
2018-10-23 17:03:08,210Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters". Target succeeded.

**Comment by timvisher** [comment]
Thanks for reporting this issue.

I would dig into what's going on with this run by dropping:

```
import ipdb; ipdb.set_trace()
1+1
```

right around [line 65](https://github.com/singer-io/tap-bronto/blob/master/tap_bronto/stream.py#L65). I would suspect there's something funky about the value that's being returned from `self.config.get('token')`.
